total_number: 4
list:
  - id: 1
    type: 1
    pose: [0, 0, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 2
    type: 0
    pose: [1, 1, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 3
    type: 0
    pose: [2, 1, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 4
    type: 1
    pose: [2, 2, 0]
    radius_speed_accel: [1, 1, 1]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
