total_number: 11
list:
  - id: 3
    type: 0
    pose: [2, 15.48, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 4
    type: 0
    pose: [6.3, 15.507, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 5
    type: 0
    pose: [6.3, 6, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 10
    type: 0
    pose: [2, 6, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 11
    type: 0
    pose: [6.3, 8.8719, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 13
    type: 0
    pose: [2, 12.2658, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 14
    type: 0
    pose: [2, 9.0447, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 15
    type: 0
    pose: [4.1613, 6, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 16
    type: 0
    pose: [4.223, 15.5, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 17
    type: 0
    pose: [4.2473, 12.3101, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
  - id: 18
    type: 0
    pose: [4.2126, 8.9331, 0]
    radius_speed_accel: [1.0, 0.2, 0.2]
    map_name: conveyor_map
    localizer_main_sub: [1, 0]
    storage_level_unload_load:
      - [100, 100]
